import type { Memory } from "~/db/schema";

export function downloadFile(content: string, filename: string, contentType: string) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportToJson(memoriesToExport: Memory[]) {
  const data = memoriesToExport.map(({ id, fact, category, tags, timestamp, lastAccessedAt, isActive }) => ({
    id,
    fact,
    category,
    tags,
    timestamp,
    lastAccessedAt,
    isActive,
  }));
  return JSON.stringify(data, null, 2);
}

export function exportToMarkdown(memoriesToExport: Memory[]) {
  const categories = ["rules", "projects", "references", "configs"];
  let doc = `# Locker Memory Vault Export\n\nGenerated on ${new Date().toLocaleString()}\n\n`;

  categories.forEach((cat) => {
    const list = memoriesToExport.filter((m) => m.category === cat);
    if (list.length === 0) return;
    doc += `## ${cat.toUpperCase()}\n\n`;
    list.forEach((m) => {
      doc += `### Memory [${m.id.slice(0, 8)}]\n`;
      doc += `- **Fact:** ${m.fact}\n`;
      if (m.tags) doc += `- **Tags:** \`${m.tags}\`\n`;
      doc += `- **Date:** ${new Date(m.timestamp).toLocaleDateString()}\n\n`;
    });
  });

  return doc;
}

export function compileRulesContent({
  scope,
  memory,
  allMemories,
  targetFile,
}: {
  scope: "single" | "all";
  memory: Memory;
  allMemories: Memory[];
  targetFile: string;
}) {
  function stripMemoryMetadata(fact: string): string[] {
    const normalised = fact
      .replace(/\s*##\s+/g, "\n## ")
      .replace(/\s*-\s+/g, "\n- ")
      .trim();

    return normalised
      .split("\n")
      .filter((line) => {
        const t = line.trim();
        return t.length > 0 && !t.startsWith("# ") && !t.startsWith("*Generated");
      })
      .map((line) => line.trim());
  }

  let lines: string[] = [];
  if (scope === "single") {
    lines = stripMemoryMetadata(memory.fact);
  } else {
    const filtered = allMemories.filter((m) => {
      if (!m.isActive) return false;
      if (m.category === "configs") return true;
      const tagsList = (m.tags || "").split(",").map((t: string) => t.trim().toLowerCase());
      return (
        tagsList.includes("architecture") ||
        tagsList.includes("baseline") ||
        tagsList.includes("config") ||
        tagsList.includes("blueprint")
      );
    });

    lines = filtered.flatMap((m, i) => {
      const content = stripMemoryMetadata(m.fact);
      return i === 0 ? content : ["", "---", "", ...content];
    });
  }

  if (targetFile === ".cursorrules") {
    return JSON.stringify(
      {
        name: scope === "single" ? "Single Rule Guideline" : "Workspace Guidelines",
        description:
          scope === "single"
            ? "Architectural rule synced from Locker"
            : "Architectural rules synced from Locker",
        globs: ["*"],
        rules: lines.filter((l) => l.trim().length > 0),
      },
      null,
      2,
    );
  } else {
    let title = "Developer Agent Rules";
    let section = "Guidelines";
    if (targetFile === "CLAUDE.md") {
      title = "Claude System Instructions";
      section = "Enforced Guidelines";
    } else if (targetFile === ".github/copilot-instructions.md") {
      title = "Copilot Instructions";
      section = "Rules";
    } else if (targetFile === "GEMINI.md") {
      title = "Gemini Rules";
      section = "Coding Guidelines";
    } else if (targetFile === "AGENTS.md") {
      title = "Developer Agent Rules";
      section = "Guidelines";
    } else if (targetFile === ".agents/rules/rules.md") {
      title = "Antigravity Rules";
      section = "Guidelines";
    }

    const sectionLines = lines.length > 0 ? [`## ${section}`, "", ...lines] : [];

    const output = [
      `# ${title} - Technical Stack Blueprint`,
      "",
      "This manifesto specifies the architectural boundaries, tech stack enforcements, and directory mapping rules for developer agents working in this repository.",
      "",
      ...sectionLines,
      "",
      "---",
      `*Generated by Locker at: ${new Date().toLocaleString()}*`,
    ];

    return output.join("\n");
  }
}
